### ISSUE TITLE
Provide stylesheet file

### ISSUE THREAD

**Issue by Ryuno-Ki** [t3chguy/riot-static#7]
Hi, @t3chguy!

I've read about your work at [Matrix.org status update](https://matrix.org/blog/2017/07/19/status-update/#comment-26907)

After visiting your [Heroku app](https://stormy-bastion-98790.herokuapp.com/) I would like to ask you, whether you could add a CSS file instead of [styling inline](https://github.com/t3chguy/riot-static/blob/54be4a267cd76536c1275bb845ab093aaf64251c/src/github.com/t3chguy/riot-static/templates/basepage.qtpl#L17)? This way, web designers could use Stylish/edit the stylesheet using browser developer tools and send a PR with an updated stylesheet without needing to know, how to build a local version of the website.

Do you have any mockups on how you would like to see the app look like?

**Comment by t3chguy** [comment]
Hi @Ryuno-Ki 

@Matthew has said he will deal with the design/css, so for now I have cared very little about the design. I will definitely pull it into a separate css file if it makes it easier for you to play with :)

**Comment by t3chguy** [comment]
I just deployed d1cfcc6 which should fix this for you @Ryuno-Ki :)
